version: '3'

services:
  app:
    build: .
    ports:
      - '3000:80'
      - '3001:3001'
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
